### ISSUE TITLE
Hi @Chiroyce about Gemini Pro Vision Project

### ISSUE THREAD

**Issue by aisystechsambit** [Chiroyce1/gemini-vision#1]
Hi @Chiroyce
Please guide us for my project regarding VHL using pro vision
provide us your contact no. or email id for discuss more

**Comment by Chiroyce1** [comment]
Hey @aisystechsambit, you can continue the discussion here or contact me on Discord @ `chiroyce`, happy to help!

**Comment by Chiroyce1** [comment]
@aisystechsambit Please let me know more about the project before I continue. I have invited you to a repo.

**Comment by aisystechsambit** [comment]
Hi we got some project related to NLP and health augmentation

**Comment by aisystechsambit** [comment]
Abhysis accademy want a native language convertion using augmented computer vision
Into English form...
Ex .... आप कैसे हो .....should be in image or video 
And then it ll convert that into specific eng native like Aap kaise ho....and like that in kannada ...
